image: gradle

stages:
  - build
  - test
  - deploy

building:
  stage: build

  script:
    - ./gradlew clean assemble -Pversion="${CI_PIPELINE_ID}-{$CI_COMMIT_BRANCH}-{$CI_COMMIT_SHORT_SHA}"
  artifacts:
    paths:
      - domain/build/libs/*.jar
    expire_in: 1 week

testing:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification
    - cat domain/build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'

check-style:
  stage: test
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest

deploy-lib:
  stage: deploy
  script:
    - mkdir libs/
    - mv domain/build/libs/*.jar libs/
  artifacts:
    paths:
      - libs/*.jar

cache:
  key: gradle
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
